project:
  type: website
  output-dir: docs

website:
  title: "Home"
  site-url: "https://lhouyangdar.github.io/my-website"
  navbar:
    pinned: true
    left:
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: litera
    toc: false